name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IRRLICHT_TAG: 1.9.0mt1

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      # - uses: Homebrew/actions/setup-homebrew@master

      - name: Install deps
        run: |
          source ./util/ci/common.sh
          # install_macos_deps

#       - name: Build
#         run: |
#           ./util/ci/build.sh

#       - name: Test
#         run: |
#           ./bin/minetest --run-unittests

      - name: Build
        run: |
          # brew install cmake libpng jpeg sqlite leveldb libogg libvorbis freetype gmp jsoncpp
          git clone https://github.com/minetest/irrlicht -b $IRRLICHT_TAG
          cd irrlicht
          cmake . -DBUILD_SHARED_LIBS=OFF
          make -j2
          cd ..
          mkdir cmakebuild
          mkdir -p artifact/minetest/usr/
          cd cmakebuild
          # cmake -DIRRLICHT_LIBRARY=$PWD/../irrlicht/lib/OSX/libIrrlichtMt.a \
          #  -DIRRLICHT_INCLUDE_DIR=$PWD/../irrlicht/include \
          #  -DCUSTOM_GETTEXT_PATH=/usr/local/opt/gettext \
          cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 \
            -DCMAKE_INSTALL_PREFIX=../artifact/minetest/usr/ \
            -DCMAKE_BUILD_TYPE=Release -DRUN_IN_PLACE=FALSE \
            -DENABLE_FREETYPE=TRUE -DENABLE_GETTEXT=TRUE \
            -DGETTEXT_MSGFMT=/usr/local/opt/gettext/bin/msgfmt \
            -DGETTEXT_INCLUDE_DIR=/usr/local/opt/gettext/include \
            -DGETTEXT_LIBRARY=/usr/local/opt/gettext/lib/libintl.a \
            -DBUILD_CLIENT=TRUE -DBUILD_SERVER=FALSE ..
          make -j2
          make install
          # make package
          # unzip minetest-*-osx.zip
          # mv minetest.app ..

#       - uses: actions/upload-artifact@v2
#         with:
#           name: minetest-macos
#           path: ./minetest.app

      - uses: actions/upload-artifact@v2
        with:
          name: minetest-macos
          path: ./artifact/*
      
