name: macos

# build on c/cpp changes or workflow changes
on:
  push:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - '.github/workflows/macos.yml'
  pull_request:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - '.github/workflows/macos.yml'

env:
  IRRLICHT_TAG: 1.9.0mt1

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          pkgs=(cmake freetype gettext hiredis jpeg leveldb libogg libpng libvorbis luajit)
          brew unlink $(brew ls --formula)
          brew update
          brew install ${pkgs[@]}
          brew link ${pkgs[@]}

          if true; then
          wget "https://github.com/FnControlOption/irrlicht/releases/download/1.9.0mt3-macos/macos-catalina.tar.gz"
          gtar -xaf macos-catalina.tar.gz -C /usr/local --touch
          fi

      - name: Build
        run: |
          if false; then
          git clone https://github.com/minetest/irrlicht -b $IRRLICHT_TAG
          cd irrlicht
          cmake . -DBUILD_SHARED_LIBS=OFF -DCMAKE_FIND_FRAMEWORK=LAST
          make -j2
          cd ..
          fi

          mkdir cmakebuild
          #mkdir -p build/macos/
          cd cmakebuild
          cmake \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 \
            -DCMAKE_FIND_FRAMEWORK=LAST \
            -DCMAKE_INSTALL_PREFIX=../build/macos/ \
            -DCMAKE_BUILD_TYPE=Release \
            -DRUN_IN_PLACE=FALSE \
            -DENABLE_FREETYPE=TRUE \
            -DENABLE_GETTEXT=TRUE \
            -DBUILD_CLIENT=TRUE \
            -DBUILD_SERVER=FALSE \
            ..
            #-DIRRLICHT_LIBRARY=$PWD/../irrlicht/lib/OSX/libIrrlichtMt.a \
            #-DIRRLICHT_INCLUDE_DIR=$PWD/../irrlicht/include \
          make -j2
          make install

      - uses: actions/upload-artifact@v2
        with:
          name: minetest-macos
          path: ./build/macos/
      
